### ISSUE TITLE
Transformation guid (column with type raw(16)) after save object

### ISSUE THREAD

**Issue by AgeevAndrew** [rsim/oracle-enhanced#1139]
Hi,

When I've built an object, or read it from database - i have got raw(16) data as usually.

But When I've saved new object, i saw that guid was transformed to hex sequence.
Is this bug or feature?

Here is a test case:
```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '~> 5.0.0'
  gem 'activerecord-oracle_enhanced-adapter', '~> 1.7.0'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  execute "DROP Table Posts"
  execute <<-SQL
    Create Table posts
    (
      GUID RAW(16) not null
    )
  SQL

  # This doesn't work. I don't understand why...
  # I get an error => undefined method `raw' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::TableDefinition:0x007.....
  # create_table :posts, :force => true do |t|
  #   t.raw :guid, limit: 16
  # end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_valid_when_build
    guid = SecureRandom.random_bytes(16)
    post = Post.new(guid: guid)

    assert_equal post.guid, guid
  end

  def test_valid_when_read
    guid = SecureRandom.random_bytes(16)
    Post.create!(guid: guid)

    post = Post.where(guid: guid).take

    assert_equal post.guid, guid
  end

  def test_invalid_when_save
    guid = SecureRandom.random_bytes(16)
    post = Post.create!(guid: guid)

    assert_equal post.guid, guid
  end
end
```

**Comment by yahonda** [comment]
This is an expected bahavior. 

RAW data type is handled here.

https://github.com/rsim/oracle-enhanced/blob/release17/lib/active_record/oracle_enhanced/type/raw.rb

If you would like to change it, you can create your own type with modified serialize method 
by following this guide.

http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html

Thanks.

**Comment by AgeevAndrew** [comment]
I have handled this raw type like this:
```
hex_fields :guid
```
Two methods are created by this line code. The first one (read method) is convert to UUID from binary sequence. The second one (write method) - from UUID to binary sequence.

But now, when I get an object from database - this methods work fine. Untill the object was saved.
After saving you serialize raw type, and I get hex sequence instead of byte sequence.

Sorry, I don't understand why this is an expected behavior. Why the same object should contain different values in different situations? Could you please explain it for me?

**Comment by yahonda** [comment]
Here Let me explain how ActiveRecord 5 works. 

In ActiveRecord 5, default attribute information is decided at `initialize_type_map` default attribute is based on database table column type. 

i.e. `posts` table `GUID` column is defined as `RAW(16)`

```sql
    Create Table posts
    (
      GUID RAW(16) not null
    )
```

Then it applies to `register_class_with_limit m, %r(raw)i,           ActiveRecord::OracleEnhanced::Type::Raw` ., this `GUID` attribute is defined as `ActiveRecord::OracleEnhanced::Type::Raw`.

https://github.com/rsim/oracle-enhanced/blob/release17/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L1193-L1212


```ruby
      def initialize_type_map(m)
        super
        # oracle
        register_class_with_limit m, %r(raw)i,            ActiveRecord::OracleEnhanced::Type::Raw
        register_class_with_limit m, %r(char)i,           ActiveRecord::OracleEnhanced::Type::String
        register_class_with_limit m, %r(clob)i,           ActiveRecord::OracleEnhanced::Type::Text

        m.register_type  'NCHAR', ActiveRecord::OracleEnhanced::Type::NationalCharacterString.new
        m.alias_type %r(NVARCHAR2)i,    'NCHAR'

        m.register_type(%r(NUMBER)i) do |sql_type|
          scale = extract_scale(sql_type)
          precision = extract_precision(sql_type)
          limit = extract_limit(sql_type)
          if scale == 0
            ActiveRecord::OracleEnhanced::Type::Integer.new(precision: precision, limit: limit)
          else
            Type::Decimal.new(precision: precision, scale: scale)
          end
        end
```

Then taking a look at `ActiveRecord::OracleEnhanced::Type::Raw` definition. Especially how `serialize` method works. Here `serialize(value)` method is executed before saving to database explained in this comment below. 

https://github.com/rails/rails/blob/5-0-stable/activemodel/lib/active_model/type/value.rb#L39-L45

```ruby
      # Casts a value from the ruby type to a type that the database knows how
      # to understand. The returned value from this method should be a
      # +String+, +Numeric+, +Date+, +Time+, +Symbol+, +true+, +false+, or
      # +nil+.
      def serialize(value)
        value
      end
```

Oracle enhanced adapter `ActiveRecord::OracleEnhanced::Type::Raw#serialize` method is implemented 
to encode the value to hex here. This is by design.
https://github.com/rsim/oracle-enhanced/commit/259cdc9b0d4830ee3621b331912b58c2bde993f1

https://github.com/rsim/oracle-enhanced/blob/release17/lib/active_record/oracle_enhanced/type/raw.rb#L12-L20

```ruby

        def serialize(value)
          # Encode a string or byte array as string of hex codes
          if value.nil?
            super
          else
            value = value.unpack('C*')
            value.map { |x| "%02X" % x }.join
          end
        end
```

Then once you save your record to the database, value will become hex one. This is the reason why I say this is an expected behavior.


If you want to change this implementation, you can implement your own type having its own serialize method.
One of the best reference is "http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute-label-Creating+Custom+Types".

**Comment by AgeevAndrew** [comment]
Hi,

Sorry for late reply. 
I have implemented my type. It works for me.

Thanks.

**Comment by yahonda** [comment]
Thanks for the update. Great you have implemented your own type.
