### ISSUE TITLE
JSON type support

### ISSUE THREAD

**Issue by deepj** [rsim/oracle-enhanced#1236]
It seems this adapter doesn't support JSON type. It would be nice to support this in near future.

**Comment by yahonda** [comment]
Would be nice. 

Due to Oracle database does not have 'JSON` data type, adding `is json` constraints to varchar2(not sure if CLOB is supported) columns. Then it is unlikely to support Rails migration but Rails 5 attribute API would be able to support some JSON features.

* Oracle
[1.2 Getting Started Using JSON with Oracle Database
](http://docs.oracle.com/database/122/ADJSN/json-in-oracle-database.htm#ADXDB6371)

* MySQL
[12.6 The JSON Data Type](https://dev.mysql.com/doc/refman/5.7/en/json.html)

**Comment by yahonda** [comment]
#1240 has been merged to master. It allows users to set `:json` attributes.
