### ISSUE TITLE
emulate_integers_by_column_name = true not working

### ISSUE THREAD

**Issue by mickael-palma-argus** [rsim/oracle-enhanced#1375]
### Steps to reproduce
I am using the adapter outside of rails.

### Expected behavior
I want to use this method :
```ruby
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.class_eval do
  self.emulate_integers_by_column_name = true
end
```

### Actual behavior
I have this error instead
```bash
NoMethodError: undefined method `emulate_integers_by_column_name=' for ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:Class
Did you mean?  emulate_booleans_from_strings=
```

### System configuration
**Rails version**: not used but I'm using activerecord 5.1.2

**Oracle enhanced adapter version**: Using activerecord-oracle_enhanced-adapter 1.8.1

**Ruby version**: Ruby 2.4.1

**Oracle Database version**: Oracle 10g

**Comment by yahonda** [comment]
`emulate_integers_by_column_name` and similar options are removed since Oracle enhanced adapter 1.7 to support Rails 5.0 Attribute API.  #871

Would you update your model definition as follows:

```ruby
class Job < ActiveRecord::Base
  attribute :job_id, :integer
end
```

Thanks

**Comment by mickael-palma-argus** [comment]
I'll try and let you know thank you for the quick feedback.
It would be nice to update the documentation to avoid mistakes.

**Comment by duffyjp** [comment]
I also work with a bunch of Oracle databases which store numerical data as strings.  I was looking through my notes just now and there have been a lot of changes in the last few years

Let's assume this is my table; where I assigned :emplid as my primary_key.


```ruby
class Person {
      :last_name => :string,
     :first_name => :string,
         :emplid => :string
}
```


* Rails 3.0 -> 4.1 and I could do `Person.find(123)` and it would work fine. Rails cast my integer to a string automatically.
* Rails 4.2 I have to do `Person.find("123")` because `set_integer_columns :emplid` didn't work.
* Rails 5.0 I can now use the Attribute API and set emplid as :integer, `Person.find(123)`

Life is good in Rails 5.
