### ISSUE TITLE
AR column caching does not work

### ISSUE THREAD

**Issue by remofritzsche** [rsim/oracle-enhanced#1585]
Thanks a bunch for any help and keep up the great work you're doing on this adapter!

### Steps to reproduce

```
# config/environments/production.rb
config.active_record.use_schema_cache_dump = true
```

```
# config/initializers/oracle.rb
ActiveSupport.on_load(:active_record) do
  ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.class_eval do
    self.cache_columns = false
  end
end
```

```
rake db:schema:cache_dump
```

### Expected behavior

No "structural" DB queries should occur when starting the application in production mode.

### Actual behavior

Countless queries like this occur:

```
SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length)....
```

I've also tried setting `cache_columns` to `true`, but this didn't do the trick either. See #1490 for more information.

### System configuration
**Rails version**: 5.0.1

**Oracle enhanced adapter version**: 1.7.10

**Ruby version**: jruby 9.1.8.0 - ruby 2.3.1

**Oracle Database version**: 12

**Comment by yahonda** [comment]
Hi,

Thanks for the report.

With Oracle enhanced adapter 1.8 or lower version, I'd suggest to keep using `OracleEnhancedAdapter.cache_columns`
since I (at least) was not aware that there is a Rails feature called schema cache which would provide the same purpose.

Starting from Oracle enhanced adapter 5.2, which will support Rails 5.2 will drop `OracleEnhancedAdapter.cache_columns` per #1490
and should support Rails schema cache. As of today, I have tested Rails schema cache with Oracle enhanced adapter all of tests have passed.

Still I do not know if "0 queries" for dictionaries is an expected behavior, then some more performance test would be appreciated
once Oracle enhanced adapter 5.2 beta and Rails 5.2 beta released.


### Environment:

* Rails master branch 
* Oracle enhanced adapter master branch 
* ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
* jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 OpenJDK 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 [linux-x86_64]
* Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production


https://github.com/rails/rails/blob/master/activerecord/test/cases/connection_adapters/schema_cache_test.rb

### Test results:

```ruby
$ ARCONN=oracle bin/test test/cases/connection_adapters/schema_cache_test.rb:32
Using oracle
Run options: --seed 22593

# Running:

.

Finished in 0.011001s, 90.8987 runs/s, 454.4936 assertions/s.

1 runs, 5 assertions, 0 failures, 0 errors, 0 skips
[yahonda@li1273-210 activerecord (mysql803)]$  ARCONN=oracle bin/test test/cases/connection_adapters/schema_cache_test.rb -v
Using oracle
Run options: -v --seed 49299

# Running:

ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_yaml_loads_5_1_dump = 0.01 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_yaml_dump_and_load = 1.10 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_clear_data_source_cache = 0.00 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_caches_columns = 0.01 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_dump_and_load = 0.31 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_data_source_exist = 0.29 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_caches_columns_hash = 0.01 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_clearing = 0.30 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_primary_key = 0.24 s = .
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_primary_key_for_non_existent_table = 0.28 s = .

Finished in 2.556201s, 3.9121 runs/s, 8.6065 assertions/s.

10 runs, 22 assertions, 0 failures, 0 errors, 0 skips
$

```

**Comment by tschoppi** [comment]
I've done some testing with the same environment as @remofritzsche. I recorded the number of "structural" queries to the database at four different points:

1. Server startup
2. Initial call to index
3. Navigating to different page that makes use of more tables in the database than just the index page
4. Navigating back to index

## Results

The conditions that varied are `config.active_record.use_schema_cache_dump` and `OracleEnhancedAdapter.cache_columns`:

use_schema_cache_dump | cache_columns | Results
---|---|---
false | false | 5 - 13 - 5 - 0
false | true  | 5 - 10 - 5 - 0
true  | false | 6 - 0 - 0 - 0
true  | true  | 6 - 0 - 0 - 0

## Discussion

The data indicate that the rails schema cache is actually used, except for some calls on server startup. Interestingly, `use_schema_cache` leads to one more call to the database, querying the `SCHEMA_MIGRATIONS` table. The other 5 calls are identical in all cases.

Furthermore, `cache_columns` has no influence when `use_schema_cache` is set to true.

## Closing

I don't know if this helps with further investigations. Maybe this all boils down to the order in which the code is loaded.

**Comment by yahonda** [comment]
Thanks for the testing and compiling the result.

> Interestingly, use_schema_cache leads to one more call to the database, querying the SCHEMA_MIGRATIONS table.

It is likely because of checking schema cache version with migration version.

https://github.com/rails/rails/blob/9f33a8f06e5bba343b0d108a41246ab8368d71d3/activerecord/lib/active_record/railtie.rb#L94
```ruby
              if cache.version == ActiveRecord::Migrator.current_version
```

> Furthermore, cache_columns has no influence when use_schema_cache is set to true.

Yes, `config.active_record.use_schema_cache_dump` and `OracleEnhancedAdapter.cache_columns` are independent.

Originally, `OracleEnhancedAdapter.cache_columns` had been introduced into Oracle enhanced adapter,
then Rails introduced `config.active_record.use_schema_cache_dump`. The purpose of them are same, to reduce queries about schema.

Starting from Oracle enhanced adapter 5.2, `OracleEnhancedAdapter.cache_columns` feature will be dropped. 
They can migrate to use `config.active_record.use_schema_cache_dump`.

I think this issue can be closed, we cannot eliminate all queries
even if we enable `config.active_record.use_schema_cache_dump = true` at startup Rails.
However, after doing some operations, number of queries for metadata are 0.

**Comment by remofritzsche** [comment]
Thanks a lot for your research and your time. We're now going with `config.active_record.use_schema_cache_dump = true` and `cache_columns = false` which is fine for us.
