### ISSUE TITLE
Use different chars for boolean strings (e.g. T/F instead of Y/N)

### ISSUE THREAD

**Issue by Poitrin** [rsim/oracle-enhanced#1794]
My company uses <tt>'T'</tt> (true) and <tt>'F'</tt> (false) as boolean values, stored in a CHAR(1) column.

Is it possible to configure oracle_enhanced (very useful gem btw, thanks for maintaining!) so that Y/N are not the only possible boolean values?

Thanks in advance!

**Comment by yahonda** [comment]
Thanks for opening an issue. Unfortunately, I would not modify boolean type anymore since Oracle enhanced adapter already extends boolean type support than Rails itself.

If you are interested in boolean type, you can refer https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/type/oracle_enhanced/boolean.rb and create your own type.

**Comment by Poitrin** [comment]
I already tried this solution, but it didn't work – all <tt>'T'</tt>/<tt>'F'</tt> values stayed the same. Now that I know that I was on the right track, I'll investigate further, and close this issue. Thanks for your answer :)
