### ISSUE TITLE
All synonyms takes longer to execute 

### ISSUE THREAD

**Issue by karthikishorejs** [rsim/oracle-enhanced#1957]
### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

### Expected behavior
When querying a table, datasource should be against user_synonyms 

### Actual behavior
 Datasource is running against all_synonyms which would take really long time to run especially if the database is large and has a lot of schemas. 
`synonyms (341249.1ms)  SELECT synonym_name, table_owner, table_name FROM all_synonyms where owner = SYS_CONTEXT('userenv', 'current_schema')
`
### System configuration
**Rails version**: 6.0.1

**Oracle enhanced adapter version**: 6.0.0

**Ruby version**: 2.6.5

**Oracle Database version**: 12.2.0.1

**Comment by yahonda** [comment]
Thanks for opening an issue.

As far as I know, Queries for `all_synonyms` tend to be slow if you are running your database using pluggable databases.  Unfortunately, Slow queries for a database dictionary is out of control from gem developers like me, would you open a Service Request with Oracle support to address this slow query.

Unfortunately, I do not have any support contract to investigate this kind of slowness.

**Comment by karthikishorejs** [comment]
all_synonyms and user_synonyms has the same schema skeleton with the only difference being the latter has less data specific to the user.  @yahonda  Do you think its beneficial to hit the user_synonyms?

**Comment by yahonda** [comment]
`all_synonyms` and other `all_xxx` dictionaries are necessary to support `:schema` options. Then no option to use `user_synonyms`, unfortunately.

**Comment by pauldoerwald** [comment]
Just leaving a note for anyone else who gets stuck by this. I had a situation where using the `all_` was causing queries to take *minutes*. To avoid the problem, I went through the code and changed every instance of `all_` for `dba_`. Now the queries return in milliseconds. 

This may not be a solution for everyone, but in my simple use case (only selecting from public views), it made a tremendous performance difference. YMMV.

**Comment by javornikolov** [comment]
As far as I recall - in Oracle 10.1 or 10.2 there has been a change (security fix) which makes all_* views slower. There have been some workarounds like:
* patching the `all_*` views in the database (yet, this exposes you to some vulnerabilities)
* Using `dba_*` views where appropriate.
* In newer versions of Oracle there have been performance improvements, yet - you can't rely all_ being as fast as dba_ (it's inherently  more complex).
* Design your database schemas in a way that you don't have too many objects in the database dictionary (avoid using recyclebin, avoid excessive amounts of synonyms /1st time I faced the issue was on database with millions of synonyms/, etc.).
