### ISSUE TITLE
Version 6.0 bug: ORA-00907 missing right parenthesis

### ISSUE THREAD

**Issue by bercob** [rsim/oracle-enhanced#2023]
### Steps to reproduce

class City < ApplicationRecord
  has_many :postal_codes, -> { order 'value asc' }, dependent: :delete_all
end

class PostalCode < ApplicationRecord
  belongs_to :city
end

City.first.destroy

### Expected behavior
City record and PostalCode child records will be destroyed.

The command should generate these sql commands:

DELETE FROM "POSTAL_CODES" 
WHERE "POSTAL_CODES"."ID" IN 
(SELECT "POSTAL_CODES"."ID" FROM "POSTAL_CODES" WHERE "POSTAL_CODES"."CITY_ID" = 506)

The version 5.2.4 generates (it's OK):

DELETE FROM "POSTAL_CODES" WHERE "POSTAL_CODES"."CITY_ID" = 506;
DELETE FROM "CITIES" WHERE "CITIES"."ID" = 506;

### Actual behavior
The command generates this sql command:

DELETE FROM "POSTAL_CODES" 
WHERE "POSTAL_CODES"."ID" IN 
(SELECT "POSTAL_CODES"."ID" FROM "POSTAL_CODES" WHERE "POSTAL_CODES"."CITY_ID" = 506 ORDER BY id asc)

Oracle throws exception:
ORA-00907: missing right parenthesis

### System configuration
**Rails version**: 6.0.3.1

**Oracle enhanced adapter version**: 6.0.2

**Ruby version**: 2.7.1

**Oracle Database version**: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0

**Comment by koic** [comment]
Thanks for the feedback.

Can you provide an executable test case to reproduce this error?
https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thank you.

**Comment by bercob** [comment]
[active_record_gem.rb.zip](https://github.com/rsim/oracle-enhanced/files/4697628/active_record_gem.rb.zip)

**Comment by joshpencheon** [comment]
We've hit this too, on an application that can work with both Postgres and Oracle. Postgres is unaffected, allowing the `ORDER BY` in the CTE, but Oracle has problems when not also using a `.limit` (which wraps in another `rownum`-filtered CTE).

I believe the originating commits in Rails were:

* [859fba7c4b](https://github.com/rails/rails/commit/859fba7c4bf7d33b4f9655914ed4bdc85380552e) – _Handle DELETE with LIMIT in Arel_
* [bfea0af4ba7](https://github.com/rails/rails/commit/bfea0af4ba7d717d6a065b4370e3ccfd8869dde6) – _Move UPDATE/DELETE with JOIN handling to the Arel side_

We're currently working around this using the following monkey patch: [`config/initializers/oracle_delete_all_shim.rb`](https://gist.github.com/joshpencheon/88f5d461d5da8154d7d28220adb4942d)

So I think this is a regression in Rails causing problems for Oracle, rather than something that `oracle-enhanced` can necessarily fix directly - @koic what's your feeling?

(From my testing, it looks like `.offset(n).delete_all` is also broken, although for different reasons - it isn't selective enough to just pull the foreign key column name from the windowing CTE.)

cc: @bshand

**Comment by koic** [comment]
I will take this later.
