### ISSUE TITLE
BINARY_FLOAT values may never be `nil` under JRuby

### ISSUE THREAD

**Issue by tillsc** [rsim/oracle-enhanced#2040]
As far as I can see #1255 introduced a bug: BINARY_FLOAT values may never be `nil` since the code uses `getFloat` to cast the value, which never returns `nil`.

**Comment by tillsc** [comment]
In the case someone needs a hotfix for this. Place the following in some initializer:

```ruby
module FixedJDBCConnection
  def get_ruby_value_from_result_set(rset, i, type_name, get_lob_value = true)
    res = super
    if type_name == :BINARY_FLOAT && rset.getString(i).nil?
      nil
    else
      res
    end
  end
end
ActiveRecord::ConnectionAdapters::OracleEnhanced::JDBCConnection.prepend(FixedJDBCConnection)
```

**Comment by ioev** [comment]
Probably a bug all in it's own, but related to BINARY_FLOAT.  I'm in the middle of upgrading a rails 4.2 project to 6.0, and it seems like the 6.0 oracle enhanced will dump a legacy float (rake db:schema:dump) as:
`t.float "progress", limit: 126`

which generates sql that looks like:
`"PROGRESS" BINARY_FLOAT(126),`

It appears that the binary_float column type doesn't accept a size parameter, because this generates an OCIError: ORA-00907: missing right parenthesis when running 'rake db:schema:load'
