### ISSUE TITLE
reset_pk_sequence for tables with non integer primary keys

### ISSUE THREAD

**Issue by scottschulthess** [rsim/oracle-enhanced#612]
We've got a legacy database with a table with a varchar primary key.  When trying to fixture-ify the data, reset_pk_sequence tries to do this

                   select NVL(max("PK_STRING_COLUMN"),0) + 1 from "TABLE"

Obviously this doesn't have a sequence and this select fails.   Is there a workaround for this currently?  If not, what sort of workaround would make sense?   Currently there is an api for set_sequence_name, however if you set it to nil, it gets set to nilstring and reset_pk_sequence still tries to find the nextval in the primary key.  I  could probably hack it up so that it if sequence_name is nilstring or nil it does not attempt these actions.

**Comment by yahonda** [comment]
It would be because ` pk_and_sequence_for` method actually just returns primary key value, returns nil for sequence name. Then `reset_pk_sequence!` gets sequence name based on default naming conventions to satisfy basic fixture works as follows.

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L776-L785

Here you can check if this `sequence_name` exists in your schema if it does not exist, sequence_name will be nil, then this select statement will be skipped.

**Comment by yahonda** [comment]
Closing this since no feedback available.

**Comment by jesmith17** [comment]
@yahonda  it's not clear to me what you are suggesting in this situation to solve the problem. 


I have the same condition. I am not defining the sequence_name in the model class as it doesn't need a sequence (string primary_key). Running tests produces the same error mentioned above. 
I should note that I am explicitly defining the primary key value in my object fixtures so it shouldn't need to run any of that code.
