### ISSUE TITLE
dead connections

### ISSUE THREAD

**Issue by frankapimenta** [rsim/oracle-enhanced#660]
I have a rails application that connects to postgres and oracle databases thru different models.
Regarding the conn to the oracle database, the firewall kills connections that are not being used after an amount of time (maybe 60m). When we try to reconnect to the oracle db the call hangs for nearly 15m to work then again. 

Is there a way that the gem covers this -> http://www.calebwoods.com/2014/10/07/oracle-connection-hanging-ruby/

I checked line 706 in https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

```ruby
code -- 
      # If SQL statement fails due to lost connection then reconnect
      # and retry SQL statement if autocommit mode is enabled.
      # By default this functionality is disabled.
      attr_reader :auto_retry #:nodoc:
      @auto_retry = false

      def auto_retry=(value) #:nodoc:
        @auto_retry = value
        @connection.auto_retry = value if @connection
      end
-- code
```
aren't this code misleading in class instance variables and instance variables (@auto_retry)?

**Comment by yahonda** [comment]
There is almost nothing that Oracle enhanced adapter gem prevents from firewall kill 'idle' sessions. I refereed the link and you can contact your system administrator and/or DBA to configure `SQLNET.EXPIRE_TIME` at database server. 

Since Oracle enhanced adapter relies on Oracle Network Services (aka SQL*Net) to connect to database. Oracle Network Services also relies on TCP/IP in most cases. Killing connections are done at this TCP/IP layer, this is out of control from Oracle enhanced adapter.

**Comment by yahonda** [comment]
Closing this issue. If you have some more questions about firewall killing existing Oracle connections, you can contact other Q&A site or other support services.

**Comment by cjbj** [comment]
@frankapimenta You could try tuning some of the timeout parameters in sqlnet.ora and perhaps look at the OS keep_alive setting.

Other "high availability" features like Oracle's FAN support would need changes to ruby-oci8.
