### ISSUE TITLE
Data type INTEGER instead of NUMBER

### ISSUE THREAD

**Issue by Bjoernsen** [rsim/oracle-enhanced#711]
I have a table `measurement_values` with a column `value`. 
My migration is pretty old (mid 2013), before I had to move from PostgreSQL to Oracle, so here is the related part of my `schema.rb` 
```sql
…
create_table "measurement_values", force: :cascade do |t|
  t.decimal "value"
   …
end
…
```

The problem is that in the database the data type of `value` is set to `INTEGER`, not `NUMBER`.
```ruby
new_value = MeasurementValue.new
new_value.value = 1.11 #=> 1.11
new_value #=> 1
new_value.value.class #=> Fixnum
```

When I change the data type of `value` in the db manually to `NUMBER`, everything works as expected
```sql
alter table 
   measurement_values
modify 
( 
   value    number
)
```

```ruby
new_value = MeasurementValue.new
new_value.value = 1.11 #=> 1.11
new_value #=> #<BigDecimal:6750bd8,'0.111E1',18(36)>
new_value.value.class #=> BigDecimal
```

I tried to update my `schema.rb` with `rake db:schema:dump` after I have changed the data type to `NUMBER` in the db to see a difference. Unfortunately, the corresponding part did not change
```sql
…
create_table "measurement_values", force: :cascade do |t|
  t.decimal "value"
   …
end
…
```
When I run `rake db:drop && rake db:schema:load`, the column `value` is set to `INTEGER` again.

I thought that the problem might be the name `value` of the column, to I renamed it to `ddasdasdasd` but without success. I got the same behavior.
Where is my mistake?

Ruby: 2.2.3p173 (I use rvm)
Rails: 4.2.4
activerecord-oracle_enhanced-adapter: 1.6.3
Oracle: 11.2

Log:
```sql
...
(16.6ms)  CREATE TABLE "MEASUREMENT_VALUES" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "VALUE" DECIMAL)
(2.5ms)  CREATE SEQUENCE "MEASUREMENT_VALUES_SEQ" START WITH 10000
(5.0ms)  CREATE TABLE "SCHEMA_MIGRATIONS" ("VERSION" VARCHAR2(255) NOT NULL) 
OracleEnhanced shortened default index name index_schema_migrations_on_version to i_schema_migrations_version
(0.9ms)              SELECT 1 FROM all_indexes i
          WHERE i.owner = XXX_DEV'
             AND i.table_owner = 'XXX_DEV'
             AND i.table_name = 'SCHEMA_MIGRATIONS'
             AND i.index_name = 'UNIQUE_SCHEMA_MIGRATIONS
...
(18.1ms)  CREATE TABLE "MEASUREMENT_VALUES" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "VALUE" DECIMAL)
(3.2ms)  CREATE SEQUENCE "MEASUREMENT_VALUES_SEQ" START WITH 10000
(7.4ms)  CREATE TABLE "SCHEMA_MIGRATIONS" ("VERSION" VARCHAR2(255) NOT NULL) 
OracleEnhanced shortened default index name index_schema_migrations_on_version to i_schema_migrations_version
(1.0ms)              SELECT 1 FROM all_indexes i
         WHERE i.owner = XXX_TEST'
            AND i.table_owner = 'XXX_TEST'
            AND i.table_name = 'SCHEMA_MIGRATIONS'
            AND i.index_name = 'UNIQUE_SCHEMA_MIGRATIONS'
...
```

**Comment by Bjoernsen** [comment]
I think I found the solution :smile: 

after changing
```ruby
create_table "measurement_values", force: :cascade do |t|
  t.decimal "value"
end
```
to 
```ruby
create_table "measurement_values", force: :cascade do |t|
  t.decimal "value", precision: 38, scale: 10
end
```

it works
```ruby
new_value = MeasurementValue.new
new_value.value = 1.11 #=> 1.11
new_value #=> #<BigDecimal:6750bd8,'0.111E1',18(36)>
new_value.value.class #=> BigDecimal
```

**Comment by yahonda** [comment]
Thanks for the report. A `DECIMAL` datatype in Oracle database is kind of a alias to `NUMBER` datatype.

http://docs.oracle.com/database/121/SQLRF/sql_elements001.htm#SQLRF00213

```sql

SQL> create table test (id decimal);

Table created.

SQL> desc test;
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID                                                 NUMBER(38)

SQL> create table test2 (id decimal(10,1));

Table created.

SQL> desc test2
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID                                                 NUMBER(10,1)

SQL>
```

Then Oracle enhanced adapter implements like this: if scale is equal to 0, Oracle datatype `NUMBER` is handled as Rails `Integer` else it is handled as Rails `decimal` datatype.

```ruby
        m.register_type(%r(NUMBER)i) do |sql_type|
          scale = extract_scale(sql_type)
          precision = extract_precision(sql_type)
          limit = extract_limit(sql_type)
          if scale == 0
            ActiveRecord::OracleEnhanced::Type::Integer.new(precision: precision, limit: limit)
          else
            Type::Decimal.new(precision: precision, scale: scale)
          end
```

Closing this since I think your solution is correct. 
Thanks.

**Comment by tillsc** [comment]
I fiddeled around with this problem on a legacy schema for quite a while. So I'll leave some hints here for the next one who struggles with this:

As far as I can see `DECIMAL` is very different to `NUMBER` since `NUMBER` (without precision and scale) can hold floating point values while `DECIMAL` (without precision and scale) is an Integer.

Changing the [`NATIVE_DATA_TYPE`]( https://github.com/rsim/oracle-enhanced/blob/cb82744c065a3514be9735362943103f7f704262/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L388) for `:decimal` to `{ name: "NUMBER" }` did the trick for me. 

*Beware*: this will handle *all* `:decimal`s fields to `NUMBER` (e.g. when importing schema dumps)! So this is no general soution to fix this. 

The only "corrent" solution I can see would be to introduce a `Type::OracleEnhanced::Number` to clearly distinguish between `DECIMAL` and `NUMBER` like Oracle seems to do itself.
