### ISSUE TITLE
rake test breaks due to missing SEQ

### ISSUE THREAD

**Issue by jesmith17** [rsim/oracle-enhanced#767]
I have model objects defined that override both the table name and the sequence name. 

``` ruby
class Merchant < ActiveRecord::Base
self.table_name = "ch_merchant"
self.sequence_name = "CH_MERCHANT_ID_SQ"
...

```

This holds true for all of my model objects.
When i run 

```
rake test
```

I get errors complaining that the "CH_MERCHANT_SEQ" sequence doesn't exist that it is trying to drop when somewhere after the 

```
rake db:test:prepare
rake db:test:load
```

I know it's after that setup as I can independently run both  db:test:load and db:test:prepare without issue.  Reviewing the created Test DB after running load and prepare, the DB looks correct. 

If I manually create the CH_MERCHANT_SEQ, and the corresponding one for each of the other tables, then the test will run. 

I suspect a defect in how the Oracle enhanced adapter is trying to interpret the schema in that it isn't reading the self.sequence_name when it runs the tests. 

I have removed the db/schema.rb file completely. 
I have also updated the db/structure.sql file via 

```
rake db:structure:dump
```

and verified that it looks correct and has the correct sequence names based on the config in the model objects. 
Nothing in any of my code references the sequences it's trying to drop.

I am running the following versions

rails 4.2.4
Ruby 2.3.0
activerecord-oracle_enhanced-adapter 1.6.6
ruby-oci8 2.2.1

Running on a Mac.

**Comment by yahonda** [comment]
Thanks for reporting. Would you update the exact error message related with "I get errors complaining that the "CH_MERCHANT_SEQ" sequence doesn't exist" and provide the necessary information to reproduce this errors.

**Comment by jesmith17** [comment]
Specific error is this. 

``` bash
MerchantTest#test_should_not_save_merchant_empty:
ActiveRecord::StatementInvalid: OCIError: ORA-02289: sequence does not exist: DROP SEQUENCE "CH_INVOICE_SEQ"
```

To re-create

Create oracle table and sequence that does not match the standard Ruby names.  (Requires overriding via the adapters self.xxxxx options
``` SQL

create table ch_merchant (
merchant_id number(11,0) NOT NULL,
merchant_name varchar(2) );

create sequence CH_MERCHANT_ID_SQ;

```
Create corresponding model for the table
``` bash
rails s scaffold merchant merchant_name

```

Update your resulting merchant model to have
``` ruby
self.table_name = 'ch_merchant'
self.sequence_name = 'ch_mercant_id_sq'
```

update your structure.sql file so that it's accurate

``` bash
rake db:structure:dump
```

Create a test against that model object and execute. 

You should see an error like the one above. Note that in my case, the error most often shows up when trying to find a sequence not related to the model I am testing but after fixtures have been applied.

**Comment by yahonda** [comment]
Thanks for the information. 

Would you also update the test definition to reproduce it .Refereed "Create a test against that model object and execute."

Thanks

**Comment by jesmith17** [comment]
Update the above comment to provide better details on re-creating the error. 

Based on quick research the bug is potentially related to line 113 in 
schema_statements.rb   (active_record/connection_adapters/oracle_enhanced/schema_statements). 

I suspect 
``` 
options[:sequence_name] 
``` 
is not being set correctly (when on the spec side only) and as a result the code tries to issue the drop sequence command against the result of 

``` 
default_sequence_name(table_name)
```

**Comment by yahonda** [comment]
Please validate the exact sequence name created and specified in your self.sequence_name are identical. 

```sql
create sequence CH_MERCHANT_ID_SQ;
```
```ruby
self.sequence_name = 'ch_mercant_id_sq'
```

Let's extract sequence names and change them to uppercase to compare.

CH_MERCHANT_ID_SQ
CH_MERCANT_ID_SQ

I think "H" is missing in the self.sequence_name. If you are still able to reproduce it after fixing this kind of typo, please report it again.

Thanks,

**Comment by jesmith17** [comment]
This error still exists. I think it's inappropriate to close it due to a typo in the re-creation steps when the reported errors shows that spelling and capitalization aren't part of the issue. 

Original error is 

``` ruby

**Comment by yahonda** [comment]
Would you create a test case using this script then we can make sure your error is not related with typo.

```ruby

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 4.2.0'
  gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
  end

  create_table :comments, :force => true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id
  end
end
```

Thanks

**Comment by jesmith17** [comment]
I was able to verify that with the fixed typo (which I fixed above) I can still re-create the error. 
It does change behavior (but not fix the problem) to use lower case in the self.sequence_name. 

Please re-open the defect.

**Comment by jesmith17** [comment]
Using the script provided won't create a valid test to show this bug, as it doesn't provide for custom table and sequence names which seems to be at the heart of the issue. 

If I was able to get the existing test suite to run, I would happily try to fix it myself and submit a patch. But I can't get the existing tests to run as they won't download rails form the forced github location.

**Comment by yahonda** [comment]
The attached script is a sample one, you can add these statements inside the model definition. Also if some pre sql statement necessary, you can write and attach the exact sql statements.

```ruby
self.table_name = 'ch_merchant'
self.sequence_name = 'ch_merchant_id_sq'
```

**Comment by jesmith17** [comment]
If I update the script, I can't run it locally as I don't have any way (based on restrictions from my work) to create my own oracle DB to get Sys and System access to. So it would be a blind copy and paste, and I would be concerned that it would get closed due to typo again. 

But if you already have the script, it should be easy to take the examples I have provided and put them into the script (with someone who can test it). 

If we create an unnecessarily high barrier for people to report defects, then how do you hope to improve the package? I have tried to be clear and provide lots of details about what I was doing and what I was seeing.

**Comment by yahonda** [comment]
You can create your own vm machine to reproduce it. https://github.com/yahonda/rails-dev-box-runs-oracle

**Comment by jesmith17** [comment]
You mis-understood my statement. it's not that I don't know how to create the test setup. It's that from a work machine perpsective I am prevented (by security settings) from doing any of the things needed to execute it (including vagrant, virtual box, Docker, or local Oracle install). 
I wish that wasn't the case, but that's out of my hands unfortunately.

**Comment by jesmith17** [comment]
I can potentially work on that script at home tonight. How would I create the structure.sql via that process, as it assumes schema.rb. But schema.rb isn't how I have to manage things I have more oracle specific things that schema.rb can handle. 

How would i include the structure.sql in this approach?

**Comment by jesmith17** [comment]
As a matter of sharing information in the hopes it might help. I am seeing in my logs that the adapter (when running in development env) is still checking for the _SEQ sequence names, and then checking for a trigger based approach, before actually using the sequence defined in the model.  I wonder if that same progression isn't happening correctly when running as a test. 

I would have thought that the adapter would have started with the defined sequence, and then done a fallback to the _SEQ name and the trigger only if the config isn't defined.

**Comment by jesmith17** [comment]
So I am still unable to get the tests to run, even with the vagrant/oracle VM approach. 
But I do think I have separately found the issue. 
The more digging i did, I figured out that it was related to attempts to insert the fixture data. As part of that, the adapter code drops the constraints on the table, then inserts the fixture data. Then it queries for the max value of the column, adds 1, then tries to drop the sequence and re-create it.  That fails becuase we use a non-standard Sequence name. 

Comments in the code show that this piece of code is not really fully correct. 

```
# *Note*: Only primary key is implemented - sequence will be nil.
          primary_key, sequence_name = pk_and_sequence_for(table_name)
          # TODO This sequence_name implemantation is just enough
          # to satisty fixures. To get correct sequence_name always
          # pk_and_sequence_for method needs some work.
```
That's from lines 790-794 of lib/active_record/connection_adapters/oracle_enhanced_adapter.rb

For now, I have worked around the issue by changing my sequence names to be the default for the adapter instead of a custom name. I did find that I still had to create a sequence for a table I have that uses a string based primary key (as it still assumed it would find a sequence for the primary key even though the data type prevents that. 

If I am able to get any of tests to run I will try to create a better test case and a patch, but I had to edit the Gemfile and remove the dependency on pulling rails from github directly just to get bundle install to run.

**Comment by mbiczysko** [comment]
I have a same problem. method **self.sequence_name = "ORDER_SEQ_TR"** does not overwrite the 
**and us.sequence_name = '#{desc_table_name}_SEQ'**, I found the same pice of code.

`
class Order < ApplicationRecord
  
self.sequence_name = "ORDER_SEQ_TR"

end`

` Sequence (109.1ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'OWNER' and us.sequence_name = 'ORDER_SEQ'`

**Comment by ekr1** [comment]
# Research / cause

I stumbled across this as well. It is easily reproducible with these steps:

- In any Rails application with an arbitrary model (with explicitely given `sequence_name`), create a fixture file for that model. One entity, arbitrary content.
- Run `rake db:fixtures:load`.

The method `reset_pk_sequence!` in `OracleEnhancedAdapter` will not receive a `sequence_name` from ActiveRecord (at least in my particular ActiveRecord version, which happens to be 4.x - I do not know whether it still happens with 5.x) calls `pk_and_sequence` to guess said values.

{code}
      def reset_pk_sequence!(table_name, primary_key = nil, sequence_name = nil) #:nodoc:
        return nil unless table_exists?(table_name)
        unless primary_key and sequence_name
        # *Note*: Only primary key is implemented - sequence will be nil.
          primary_key, sequence_name = pk_and_sequence_for(table_name)
          # TODO This sequence_name implemantation is just enough
          # to satisty fixures. To get correct sequence_name always
          # pk_and_sequence_for method needs some work.
          begin
            sequence_name = table_name.classify.constantize.sequence_name
          rescue
            sequence_name = default_sequence_name(table_name)
          end
        end
. . . 
{code}

`pk_and_sequence_for` guesses the primary key correctly (unrelated to this issue). But it wants to calculate the sequence name from the table_name by appending `_SEQ`, which is the ActiveRecord default, but in our case is not correct. We gave a custom sequence name in the model, after all.

The root of the problem is that ActiveRecord does not pass the actual sequence name to `reset_pk_sequence!`. I do not know whether the second and third parameters of this method are "official" or whether they are inventions by `OracleEnhancedAdapter`. The ActiveRecord code is thus (grepping for all occurrences of `reset_pk_sequence!`):

./versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:487:            if connection.respond_to?(:reset_pk_sequence!)
./versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:489:                connection.reset_pk_sequence!(fs.table_name)

As you see, `ActiveRecord` does not bother about the sequence name at all.

# Impact

This means that is is simply impossible to use test fixtures in any ActiveRecord/Rails project which uses OracleEnhancedAdapter for models with custom sequence names.

# Solution

Either ActiveRecord needs to pass along the sequence name, or OracleEnhancedAdapter has to find the model class (given only the table name) and pick the sequence name from there.

Here is a working solution for the second approach:

First, this implementation replaces the existing `OracleEnhancedAdapter.pk_and_sequence_for_without_cache`:

{code}
      def pk_and_sequence_for_without_cache(table_name, owner=nil, desc_table_name=nil, db_link=nil) #:nodoc:

        result = nil
        
        ActiveRecord::Base.descendants.each do |model|
          if model.table_name.eql? table_name
            if result
              raise "Table '#{table_name}' has multiple models; this case is not supported in OracleEnhancedAdapter.pk_and_sequence_for_without_cache"
            else
              result = [ model.primary_key.downcase, model.sequence_name.downcase ]
            end
          end
        end
        
        return result
      end
{code}

(Of course, one might ponder whether the previous implementation, which makes at least partly sense for the primary key, might provide any benefit over querying the model.)

Then, there is a little bug in `OracleEnhancedAdapter.reset_pk_sequence!`, which calls `pk_and_sequence_for` and then summarily throws away the result. A small `if` corrects this:

{code}
      def reset_pk_sequence!(table_name, primary_key = nil, sequence_name = nil) #:nodoc:

        return nil unless table_exists?(table_name)
        unless primary_key and sequence_name
        # *Note*: Only primary key is implemented - sequence will be nil.
          primary_key, sequence_name = pk_and_sequence_for(table_name)
          # TODO This sequence_name implemantation is just enough
          # to satisty fixures. To get correct sequence_name always
          # pk_and_sequence_for method needs some work.
          if sequence_name.nil?      ######################## <== add this
            begin
              sequence_name = table_name.classify.constantize.sequence_name
            rescue
              sequence_name = default_sequence_name(table_name)
            end
          end
        end
{code}

# Why no pull request?

The whole approach has its flaw. In my particular application, those sequences are actually oracle synonyms, pointing to another sequence. To make it worse, all my models share the *same* sequence (via synonyms with different names). Don't ask why, it just is - it's an old, non-ActiveRecord application, which has been converted to ActiveRecord.

So, my choice to solve this problem is to monkey-patch `reset_pk_sequence!` away completely - just make it a no-op. I do not need the feature anyway - the tables for which I have fixtures are not receiving any further entities anyway, so I do not actually need to get a collision-free sequence.

# That said...

I hope this clears the issue up and someone picks up the ball from here to at *least* implement the model-querying. For sane cases, where the actual sequence has a custom name but is a real sequence (and not a synonym), my solution should work perfectly. 

One might even go so far as to recognize the case of the sequence_name actually being a synonym, and then turning off the feature, like I did with my eventual monkey-patch.
