### ISSUE TITLE
Failed to load OCI8

### ISSUE THREAD

**Issue by Javix** [rsim/oracle-enhanced#814]
I tried to figure out why my connection does not work and executed the script provided in [README](https://github.com/rsim/oracle-enhanced/blob/master/README.md):
```
ruby -rubygems -e "require 'oci8'; OCI8.new('username','password','database').exec('select * from dual') do |r| puts r.join(','); end"
```
It  failed as follows:
```
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- oci8lib_230 (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.1-x64-mingw32/lib/oci8.rb:72:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from -e:1:in `<main>'
```

Reproduced on:
* Windows 7 x64
* Ruby 2.3

Installed related gems:
* ruby-oci8 (2.2.1 x64-mingw32)
* activerecord-oracle_enhanced-adapter (1.6.7)

Any idea ? Thank you.

**Comment by yahonda** [comment]
If you just reproduce this error using this command, would you contact https://github.com/kubo/ruby-oci8 

```ruby
ruby -rubygems -e "require 'oci8'; OCI8.new('username','password','database').exec('select * from dual') do |r| puts r.join(','); end"
```

This command does not execute any ActiveRecord related code.

**Comment by kubo** [comment]
* ruby-oci8 (2.2.1 x64-mingw32)

The latest binary gem doesn't include pre-compiled `oci8lib_230.so` because rubyinstaller.org released ruby 2.3.0 just a week ago.

There are three ways:
* Use ruby 2.2.4, which uses pre-compiled `oci8lib_220.so` included in the latest binary gem.
* Wait ruby-oci8 2.2.2, which will be released this or next weekend.
* Compile `oci8lib_230.so` by yourself: Install [devkit-mingw64-64](http://rubyinstaller.org/downloads/) and run `gem install ruby-oci8 --platform ruby`. (Some more steps will be required. I haven't tested it.)

**Comment by yahonda** [comment]
Thanks for the update. Appreciated.

**Comment by Javix** [comment]
Thank you guys for your feed back, looking forward the new version.

**Comment by kubo** [comment]
@Javix 
I pushed the new version just now.

**Comment by Javix** [comment]
Great, I'll try it tomorrow, thanks.
